server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true

spring:
  profiles:
    include: elastic
    active: prod
  application:
    name: knowledge-docker
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  session:
    store-type: redis
  task:
    execution:
      thread-name-prefix: knowledge-task-
      pool:
        core-size: 1
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: knowledge-scheduling-
      pool:
        size: 1
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql:3306/knowledge?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  redis:
    database: 0
    host: redis
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
      enabled: true
storage:
  location: /knowledge/storage

