server:
  port: 8080
  address: 0.0.0.0
  undertow:
    io-threads: 2
    direct-buffers: true
  compression:
    enabled: true

spring:
  profiles:
    active: docker
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        keep-alive: 180s
        queue-capacity: 512
      thread-name-prefix: knowledge-
  application:
    name: knowledge-docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/knowledge?useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  cache:
    type: simple
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/actuator/0z6DX129xRDOsv5dpPrr
      exposure:
        include:
          - loggers
          - health
          - info
storage:
  location: /knowledge/storage
logging:
  level:
    top.techial: info

