server:
  port: 8080
  address: 0.0.0.0
  undertow:
    io-threads: 2
    direct-buffers: true
  compression:
    enabled: true

spring:
  application:
    name: knowledge-docker
  data:
    neo4j:
      username: neo4j
      password: techial
      uri: bolt://neo4j:7687
      open-in-view: true
      auto-index: update
    mongodb:
      host: mongo
      port: 27017
      database: knowledge
  cache:
    type: simple
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/actuator/0z6DX129xRDOsv5dpPrr
      exposure:
        include:
          - loggers
          - health
          - info
logging:
  level:
    org.neo4j.ogm: info
    top.techial: info

