server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true

spring:
  resources:
    cache:
      cachecontrol:
        cache-public: true
        max-age: 1h
  profiles:
    include:
      - elastic
      - prod
  application:
    name: knowledge-docker
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  task:
    execution:
      thread-name-prefix: knowledge-task-
      pool:
        core-size: 8
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: knowledge-scheduling-
      pool:
        size: 8
  datasource:
    url: jdbc:mysql://mysql:3306/knowledge?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    database: 0
    host: redis://redis:6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
      enabled: true

storage:
  location: /knowledge/storage

