server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration, org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
  application:
    name: knowledge-docker
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  profiles:
    active: docker
  session:
    store-type: redis
  task:
    execution:
      thread-name-prefix: knowledge-task-
      pool:
        core-size: 1
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: knowledge-scheduling-
      pool:
        size: 1
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql:3306/knowledge?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  redis:
    database: 0
    host: redis
    jest:
      uris: http://elastic:9200
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  cache:
    jcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
      enabled: true
storage:
  location: /knowledge/storage

