version: '3.7'

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certificate:/etc/nginx/certificate
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/var/www

