version: '3.7'
services:
  web:
    image: techial.top/knowledge:latest
    networks:
      - knowledge
    depends_on:
      - mysql
      - redis
      - elastic
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources/application.yml:/app/resources/application.yml:ro
      - ./deploy/resources/ehcache.xml:/app/resources/ehcache.xml:ro
      - ./deploy/resources/logback.xml:/app/resources/logback.xml:ro
      - /root/knowledge-storage:/knowledge/storage
    healthcheck:
      test: "curl -f http://localhost:8080/api/user/me || exit 1"
      retries: 3
      interval: 30s
      timeout: 30s
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

  redis:
    image: redis:alpine
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis_data:/data

  elastic:
    image: elasticsearch:latest
    ports:
      - 9200:9200
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - elastic_data:/usr/share/elasticsearch/data

networks:
  knowledge:
    external: true

volumes:
  elastic_data:
    external: true
  redis_data:
    external: true
  mysql_data:
    external: true
