version: '3.7'
services:
  web:
    image: techial.top/knowledge:latest
    networks:
      - knowledge
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources:/app/resources:ro
      - web_data:/web-logs
      - /root/knowledge-storage:/knowledge/storage
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

networks:
  knowledge:
    external: true

volumes:
  web_data:
    external: true
  mysql_data:
    external: true
