version: '3.7'
services:
  web:
    image: top.techial/knowledge/api:latest
    networks:
      - knowledge
    depends_on:
      - neo4j
      - mysql
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources:/app/resources:ro
      - web_data:/web-logs
    restart: always

  mysql:
    image: mysql:5.7
    networks:
      - activity
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

  neo4j:
    image: neo4j:latest
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/techial
    restart: always

networks:
  knowledge:
    external: true

volumes:
  web_data:
    external: true
  mysql_data:
    external: true
  neo4j_logs:
    external: true
  neo4j_conf:
    external: true
  neo4j_import:
    external: true
  neo4j_plugins:
    external: true

