version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/knowledge.conf:/etc/nginx/conf.d/knowledge.conf
      - ./deploy/nginx/zh_CN.js:/usr/share/nginx/html/static/js/zh_CN.js
    depends_on:
      - web
    ports:
      - "4000:8080"
    networks:
      - knowledge
  web:
    image: techial.cc/knowledge:latest
    networks:
      - knowledge
    depends_on:
      - mysql
      - redis
      - elastic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources/application.yml:/app/resources/application.yml:ro
      - ./deploy/resources/application-elastic.yml:/app/resources/application-elastic.yml:ro
      - ./deploy/resources/ehcache.xml:/app/resources/ehcache.xml:ro
      - ./deploy/resources/logback.xml:/app/resources/logback.xml:ro
      - /root/knowledge-storage:/knowledge/storage
    healthcheck:
      test: "curl -f http://localhost:8080/api/user/me || exit 1"
      retries: 3
      interval: 30s
      timeout: 30s
    restart: always

  mysql:
    image: mysql:8.0
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - knowledge_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

  redis:
    image: redis:alpine
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - knowledge_redis_data:/data

  elastic:
    image: elasticsearch:latest
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - knowledge_elastic_data:/usr/share/elasticsearch/data
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'

networks:
  knowledge:
    external: true

volumes:
  knowledge_elastic_data:
    external: true
  knowledge_redis_data:
    external: true
  knowledge_mysql_data:
    external: true
