version: '3.7'
services:
  web:
    image: top.techial/knowledge/api:latest
    networks:
      - knowledge
    depends_on:
      - neo4j
      - mongo
    ports:
      - 9090:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources:/app/resources:ro
      - knowledge_web_data:/web-logs
    restart: always

  mongo:
    image: mongo:latest
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - knowledge_mongo_data:/data/db
    restart: always

  neo4j:
    image: neo4j:latest
    networks:
      - knowledge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - knowledge_neo4j_logs:/logs
      - knowledge_neo4j_conf:/var/lib/neo4j/conf
      - knowledge_neo4j_import:/var/lib/neo4j/import
      - knowledge_neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/techial
    restart: always

networks:
  knowledge:
    external: true

volumes:
  knowledge_web_data:
    external: true
  knowledge_mongo_data:
    external: true
  knowledge_neo4j_logs:
    external: true
  knowledge_neo4j_conf:
    external: true
  knowledge_neo4j_import:
    external: true
  knowledge_neo4j_plugins:
    external: true

