server:
  port: 8080
  address: 0.0.0.0
  undertow:
    io-threads: 12
    direct-buffers: true

spring:
  data:
    neo4j:
      username: neo4j
      password: techial
      uri: bolt://localhost:7687
      open-in-view: true
      auto-index: dump
    mongodb:
      host: localhost
      port: 27017
      database: activity
  cache:
    type: simple
logging:
  level:
    org.neo4j.ogm: debug
    org.springframework.data: debug
    top.techial: debug

