server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true

spring:
  profiles:
    include: elastic
    active: dev
  application:
    name: knowledge-dev
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  task:
    execution:
      thread-name-prefix: knowledge-task-
      pool:
        core-size: 12
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: knowledge-scheduling-
      pool:
        size: 12
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/knowledge?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    database: 0
    host: redis://localhost:6379
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
      enabled: true
storage:
  location: /Users/techial/Downloads/knowledge
logging:
  level:
    top.techial: debug

