server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true

spring:
  application:
    name: knowledge-dev
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        keep-alive: 180s
        queue-capacity: 512
      thread-name-prefix: knowledge-
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/knowledge?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
      enabled: true
storage:
  location: /Users/techial/Downloads/knowledge
logging:
  level:
    top.techial: debug

