server:
  port: 8080
  address: 0.0.0.0
  undertow:
    io-threads: 12
    direct-buffers: true
  compression:
    enabled: true

spring:
  application:
    name: knowledge-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/knowledge?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  data:
    neo4j:
      username: neo4j
      password: techial
      uri: bolt://localhost:7687
      open-in-view: true
      auto-index: assert
  cache:
    type: simple
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
      enabled: true
management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/v3/actuator/0z6DX129xRDOsv5dpPrr
      exposure:
        include:
          - loggers
          - health
          - info

storage:
  location: /Users/techial/Downloads/knowledge
logging:
  level:
    org.neo4j.ogm: debug
    top.techial: debug

