server:
  port: 8080
  address: 0.0.0.0
  undertow:
    io-threads: 2
    direct-buffers: true
  compression:
    enabled: true

spring:
  application:
    name: knowledge-docker
  data:
    neo4j:
      username: neo4j
      password: techial
      uri: bolt://neo4j:7687
      open-in-view: true
      auto-index: update
    mongodb:
      host: mongo
      port: 27017
      database: knowledge
  cache:
    type: simple

logging:
  level:
    org.neo4j.ogm: debug
    top.techial: debug

