server:
  port: 8080
  address: 0.0.0.0
  undertow:
    io-threads: 12
    direct-buffers: true
  compression:
    enabled: true

spring:
  application:
    name: knowledge-dev
  data:
    neo4j:
      username: neo4j
      password: techial
      uri: bolt://localhost:7687
      open-in-view: true
      auto-index: assert
    mongodb:
      host: localhost
      port: 27017
      database: knowledge
  cache:
    type: simple
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/v3/actuator/0z6DX129xRDOsv5dpPrr
      exposure:
        include:
          - loggers
          - health
          - info

storage:
  location: /Users/techial/Downloads/knowledge
logging:
  level:
    org.neo4j.ogm: debug
    top.techial: debug

