server:
  port: 8080
  address: 0.0.0.0
  undertow:
    io-threads: 12
    direct-buffers: true
  compression:
    enabled: true

spring:
  application:
    name: knowledge-dev
  data:
    neo4j:
      username: neo4j
      password: techial
      uri: bolt://localhost:7687
      open-in-view: true
      auto-index: assert
    mongodb:
      host: localhost
      port: 27017
      database: knowledge
  cache:
    type: simple
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    org.neo4j.ogm: debug
    top.techial: debug

