name: CI

on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/knowledge && chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh
