name: Knowledge Docker


on:
  push:
    tags:
      - "v*"
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push docker image
        run: |
          docker login docker.pkg.github.com --username=${{ secrets.GITHUB }} --password=${{ secrets.TOKEN }}
          chmod +x ./deploy/build.sh && ./deploy/build.sh

